import React, { useState, useRef } from 'react';
import {
  FileText,
  Download,
  UploadCloud,
  Trash2,
  Check,
  FolderOpen,
  Image as ImageIcon,
  FileCode,
  FileSpreadsheet,
} from 'lucide-react';
import { useApp } from '../../context/AppContext';

export const DocumentsView: React.FC = () => {
  const { documents, uploadDocument, deleteDocument } = useApp();
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [selectedCategory, setSelectedCategory] = useState('All');
  const [isDragging, setIsDragging] = useState(false);
  const [uploadToast, setUploadToast] = useState<string | null>(null);

  const categories = ['All', 'Design Files', 'Specifications', 'Client Briefs', 'Uploaded Documents'];

  const filteredDocs =
    selectedCategory === 'All'
      ? documents
      : documents.filter((d) => d.category === selectedCategory || (!d.category && selectedCategory === 'Uploaded Documents'));

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (files && files.length > 0) {
      const file = files[0];
      await uploadDocument(file, selectedCategory === 'All' ? 'Uploaded Documents' : selectedCategory);
      setUploadToast(`Uploaded "${file.name}" successfully!`);
      setTimeout(() => setUploadToast(null), 3000);
      e.target.value = '';
    }
  };

  const handleDrop = async (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    const files = e.dataTransfer.files;
    if (files && files.length > 0) {
      const file = files[0];
      await uploadDocument(file, selectedCategory === 'All' ? 'Uploaded Documents' : selectedCategory);
      setUploadToast(`Uploaded "${file.name}" successfully!`);
      setTimeout(() => setUploadToast(null), 3000);
    }
  };

  const getFileIcon = (name: string, type: string) => {
    const ext = name.split('.').pop()?.toLowerCase() || type.toLowerCase();
    if (['png', 'jpg', 'jpeg', 'svg', 'webp', 'gif'].includes(ext)) {
      return <ImageIcon className="w-5 h-5 text-purple-600" />;
    }
    if (['fig', 'sketch', 'xd'].includes(ext)) {
      return <FileText className="w-5 h-5 text-indigo-600" />;
    }
    if (['pdf'].includes(ext)) {
      return <FileText className="w-5 h-5 text-rose-600" />;
    }
    if (['csv', 'xlsx', 'xls'].includes(ext)) {
      return <FileSpreadsheet className="w-5 h-5 text-emerald-600" />;
    }
    if (['js', 'ts', 'tsx', 'jsx', 'html', 'json'].includes(ext)) {
      return <FileCode className="w-5 h-5 text-blue-600" />;
    }
    return <FileText className="w-5 h-5 text-blue-600" />;
  };

  const handleDownload = (doc: { name: string; url?: string }) => {
    if (doc.url) {
      const a = document.createElement('a');
      a.href = doc.url;
      a.download = doc.name;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
    } else {
      // Create a fallback text blob to download
      const blob = new Blob([`Sample content for ${doc.name}\nGenerated by Productivity OS`], {
        type: 'text/plain;charset=utf-8',
      });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = doc.name;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }
  };

  return (
    <div className="space-y-5 pb-12">
      {/* Toast Notification */}
      {uploadToast && (
        <div className="fixed top-20 right-8 z-50 bg-slate-900 text-white px-4 py-3 rounded-2xl shadow-xl flex items-center gap-2 text-xs font-semibold animate-in fade-in slide-in-from-top-4 duration-200">
          <Check className="w-4 h-4 text-emerald-400" />
          <span>{uploadToast}</span>
        </div>
      )}

      {/* Top action bar */}
      <div className="bg-white rounded-2xl p-4 border border-slate-200/80 shadow-xs flex flex-wrap items-center justify-between gap-4">
        <div>
          <h3 className="font-bold text-slate-800 text-sm">Project Documents & File Assets</h3>
          <p className="text-xs text-slate-400">
            Upload, preview, and download project specifications, design mocks, and attachments
          </p>
        </div>

        <div className="flex items-center gap-3">
          <input
            type="file"
            ref={fileInputRef}
            onChange={handleFileChange}
            className="hidden"
          />
          <button
            onClick={() => fileInputRef.current?.click()}
            className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-xs font-semibold flex items-center gap-1.5 shadow-sm shadow-blue-500/25 transition-all"
          >
            <UploadCloud className="w-4 h-4" />
            <span>Upload New File</span>
          </button>
        </div>
      </div>

      {/* Drag and Drop Zone */}
      <div
        onDragOver={(e) => {
          e.preventDefault();
          setIsDragging(true);
        }}
        onDragLeave={() => setIsDragging(false)}
        onDrop={handleDrop}
        onClick={() => fileInputRef.current?.click()}
        className={`border-2 border-dashed rounded-3xl p-8 text-center cursor-pointer transition-all ${
          isDragging
            ? 'border-blue-500 bg-blue-50/70 scale-[1.01]'
            : 'border-slate-200 bg-white hover:bg-slate-50/60 hover:border-blue-300'
        }`}
      >
        <div className="w-12 h-12 rounded-2xl bg-blue-50 text-blue-600 flex items-center justify-center mx-auto mb-3">
          <UploadCloud className="w-6 h-6" />
        </div>
        <h4 className="text-sm font-bold text-slate-800">
          Drag and drop your project files here, or <span className="text-blue-600 underline">browse</span>
        </h4>
        <p className="text-xs text-slate-400 mt-1">
          Supports Figma (.fig), PDF, Word (.docx), Excel, images, archives up to 100MB
        </p>
      </div>

      {/* Categories Filter Tabs */}
      <div className="flex items-center gap-2 overflow-x-auto pb-1">
        {categories.map((cat) => (
          <button
            key={cat}
            onClick={() => setSelectedCategory(cat)}
            className={`px-3 py-1.5 rounded-xl text-xs font-medium whitespace-nowrap transition-all ${
              selectedCategory === cat
                ? 'bg-blue-600 text-white font-semibold shadow-xs'
                : 'bg-white border border-slate-200 text-slate-600 hover:bg-slate-50'
            }`}
          >
            {cat}
          </button>
        ))}
      </div>

      {/* Files List */}
      <div className="bg-white rounded-2xl border border-slate-200/80 shadow-xs divide-y divide-slate-100 overflow-hidden">
        {filteredDocs.length === 0 ? (
          <div className="py-12 text-center text-slate-400">
            <FolderOpen className="w-8 h-8 mx-auto mb-2 text-slate-300" />
            <p className="text-xs font-medium">No files in this category</p>
            <p className="text-[11px] text-slate-400 mt-0.5">Upload a file above to get started</p>
          </div>
        ) : (
          filteredDocs.map((doc) => (
            <div
              key={doc.id}
              className="p-4 flex items-center justify-between hover:bg-slate-50/80 transition-colors group"
            >
              <div className="flex items-center gap-3.5 min-w-0">
                <div className="w-10 h-10 rounded-xl bg-slate-50 border border-slate-100 flex items-center justify-center shrink-0">
                  {getFileIcon(doc.name, doc.type)}
                </div>
                <div className="min-w-0">
                  <h4 className="text-xs font-bold text-slate-800 truncate group-hover:text-blue-600 transition-colors">
                    {doc.name}
                  </h4>
                  <div className="flex items-center gap-2 text-[11px] text-slate-400 mt-0.5">
                    <span>{doc.size}</span>
                    <span>•</span>
                    <span>{doc.uploadedAt}</span>
                    <span>•</span>
                    <span className="font-medium text-slate-500">{doc.uploadedBy}</span>
                    {doc.category && (
                      <span className="text-[10px] bg-slate-100 text-slate-600 px-2 py-0.2 rounded-full">
                        {doc.category}
                      </span>
                    )}
                  </div>
                </div>
              </div>

              <div className="flex items-center gap-1.5 shrink-0">
                <button
                  onClick={() => handleDownload(doc)}
                  className="p-2 text-slate-500 hover:text-blue-600 hover:bg-blue-50 rounded-xl transition-colors flex items-center gap-1 text-xs font-medium"
                  title="Download File"
                >
                  <Download className="w-4 h-4" />
                  <span className="hidden sm:inline">Download</span>
                </button>
                <button
                  onClick={() => deleteDocument(doc.id)}
                  className="p-2 text-slate-400 hover:text-rose-600 hover:bg-rose-50 rounded-xl transition-colors"
                  title="Delete File"
                >
                  <Trash2 className="w-4 h-4" />
                </button>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
};
